### ISSUE TITLE
Translate['Made with LOVE in Germany'] -> RU lang

### ISSUE THREAD

**Issue by Hollicsh** [Wolkenschutz/KeystoneLoot#17]
Hey [Wolkenschutz](https://github.com/Wolkenschutz) !

This phrase ('Сделано с ЛЮБОВЬЮ в Германии') sounds unnatural in Russian.
The only correct solution for this phrase would be **KeystoneLoot © 2024**

**Comment by Wolkenschutz** [comment]
Heii Hollicsh,

My problem is that it's not a copyright. This is simply a note that it's a German production. What to use instead?

Best regards,
Shantalya

**Comment by Hollicsh** [comment]
Ok, no problem, let it be so )
