### ISSUE TITLE
Monk-Windwalker catalyst conversion tooltips broken

### ISSUE THREAD

**Issue by rideekulous** [Wolkenschutz/KeystoneLoot#22]
Monk-Windwalker catalyst conversion tooltips are broken for Wrist, Waist, and Feet.

Wrist is showing waist icon, no tooltip.
![image](https://github.com/Wolkenschutz/KeystoneLoot/assets/165203372/4910a783-850f-4c03-94a0-d2dc9e41121d)

Waist is showing wrist icon, no tooltip.
![image](https://github.com/Wolkenschutz/KeystoneLoot/assets/165203372/5194e980-556a-4bed-91f3-2faf4b85eb84)

Feet is showing correct icon, but has no tooltip.
![image](https://github.com/Wolkenschutz/KeystoneLoot/assets/165203372/a1a85be5-8ef9-49f0-87b4-0d467c509700)

**Comment by Wolkenschutz** [comment]
Heii rideekulous,

Thank you for reporting the bug! Will be fixed in the next update.

Best regards,
Shantalya

**Comment by rideekulous** [comment]
Thanks for the quick fix! However, just FYI, while the WW tooltips are good now the icon/art for the wrist and waist are still mixed up.
