### ISSUE TITLE
Simplified Chinese

### ISSUE THREAD

**Issue by gt1226500986** [Wolkenschutz/KeystoneLoot#24]
Is there a simplified Chinese version?

**Comment by Wolkenschutz** [comment]
zhCN is the Simplified Chinese version?

**Comment by Wolkenschutz** [comment]
![Screenshot_20240706_110510](https://github.com/Wolkenschutz/KeystoneLoot/assets/86602366/e020f58e-69e9-4f0f-8854-470df7a2393d)

**Comment by gt1226500986** [comment]
Is it possible to filter which copies have filtered items based on attributes and parts?
