### ISSUE TITLE
rationalization

### ISSUE THREAD

**Issue by gt1226500986** [Wolkenschutz/KeystoneLoot#27]
There is a plug-in:https://www.curseforge.com/wow/addons/enhanced-mythic-plus-loot
Its function is the same as yours, but he can choose equipment based on attributes. Will you also add this in the update?

**Comment by Wolkenschutz** [comment]
Heii gt1226500986,

When you select your class, you only see your attributes.

As a Holy Paladin then seeing mage things with intelligence doesn't really make sense?

Best regards,
Shantalya

**Comment by Wolkenschutz** [comment]
Added with version 1.9.0
