### ISSUE TITLE
1x KeystoneLoot/frames/dungeon/filter_class.lua:14: bad argument #3 to 'format' (string expected, got nil)

### ISSUE THREAD

**Issue by Hollicsh** [Wolkenschutz/KeystoneLoot#8]
Last ver. addOn

> 1x KeystoneLoot/frames/dungeon/filter_class.lua:14: bad argument #3 to 'format' (string expected, got nil)
> [string "=[C]"]: in function `format'
> [string "@KeystoneLoot/frames/dungeon/filter_class.lua"]:14: in function <KeystoneLoot/frames/dungeon/filter_class.lua:7>
> [string "@KeystoneLoot/frames/dungeon/filter_class.lua"]:36: in function `Init'
> [string "@KeystoneLoot/api/filter.lua"]:21: in function <KeystoneLoot/api/filter.lua:18>
> 
> Locals:
> (*temporary) = "|c%s%s|r (%s)"
> (*temporary) = "ffa330c9"
> (*temporary) = "Охотник на демонов"
> (*temporary) = nil
> (*temporary) = "string expected, got nil"
>

**Comment by Wolkenschutz** [comment]
I don't understand why you don't have a spec name...? Can you check if it works now?

Best regards,
Shantalya

**Comment by Hollicsh** [comment]
There were no errors before the latest update.
Ver. 1.4.4 -> fine. Ver. 1.5.0 -> error.

Ty for fix in ver. 1.5.1
